### ISSUE TITLE
Mod Loader exe not functioning

### ISSUE THREAD

**Issue by Etherios55** [shalzuth/RiskOfShame#1]
When i start RiskOfShame.Loader.exe with risk of rain open it does nothing but stay on the screen saying "Waiting for Risk of Rain 2 to open. I've tried opening it before risk of rain and after, the result is the same.

**Comment by shalzuth** [comment]
Fixed some stuff in this new build - try again?

**Comment by Etherios55** [comment]
Works perfectly now. Thank you!
