### ISSUE TITLE
[Request] BepInEx support

### ISSUE THREAD

**Issue by nihaals** [shalzuth/RiskOfShame#12]
Hi,
I was wondering if you were able to have some form of a modloader compatible mod (for example BepInEx) to reduce the range of modloaders people use with their game. This would also reduce maintenance for the built-in loader and make it more convenient to use the mod (so you do not have to run a .exe every time to inject the mod). It may also be beneficial to separate the features into their own mods (something like [SharedModLibrary](https://github.com/ToyDragon/ROR2ModShared) could deal with enabling and disabling)

Thanks

**Comment by shalzuth** [comment]
I’m not going to modify the game directory, it’s privileged, can get corrupted, etc. it’s messy. Which is how the one you mentioned works.
The method I’m using is perfectly compatible with quite a few modloaders out there, if you search any unity injector.
What some other modloaders are doing is adding their own sauce on top of this method. Feel free to ask other modloaders to support the method I’m employing. Or you can create a wrapper around RiskOfShame to be compatible with other custom modloaders.
Or, ask the Hopoo devs for official mod support or to integrate some of the QoL mods into the base game.

As for separating the features, they are separated. In game, you enable/disable each mod much like the in the picture you linked. It doesn’t have customization yet, but I plan to add it at some point.
