### ISSUE TITLE
Cant inject 

### ISSUE THREAD

**Issue by M1ND4UG4S** [shalzuth/RiskOfShame#14]
![Risk of Rain 2 Problem](https://user-images.githubusercontent.com/30414082/56676711-95d80c80-66c7-11e9-8612-3df45d88b15e.PNG)

**Comment by shalzuth** [comment]
Bad pull request messed it up.
https://github.com/shalzuth/RiskOfShame/commit/11b4fce08ef7f28d77b7b0608f4d58c0f007a863
Reverted, try again?
