### ISSUE TITLE
Hangs at Injecting

### ISSUE THREAD

**Issue by TadaceAce** [shalzuth/RiskOfShame#2]
No luck getting this to work. Fresh install of RoR2, Win7 x64, ran as admin. Just hangs at Injecting - Gate @....

**Comment by shalzuth** [comment]
Is the game path correct?
Have you tried running it through visual studio with the debugger to pinpoint the exact failure location?

**Comment by shalzuth** [comment]
Can you try the latest version? https://github.com/shalzuth/RiskOfShame/releases/download/beta/RiskOfShame.Loader.exe
