### ISSUE TITLE
Not working after patch 4/16/2019

### ISSUE THREAD

**Issue by thisandthatXD** [shalzuth/RiskOfShame#5]
hope you can update the mod its one of the better ones right now

**Comment by shalzuth** [comment]
updated. might need to update loader, added c# 6 features which requires different compilation.

**Comment by thisandthatXD** [comment]
awesome well done

**Comment by thisandthatXD** [comment]
https://github.com/shalzuth/RiskOfShame/releases/download/alpha/RiskOfShame.Loader.exe

link is broken atm or just not updated on thunderstore.

**Comment by shalzuth** [comment]
Tagged it beta and updated on thunderstore
