### ISSUE TITLE
The Loader.exe is stuck at injecting, the file path is correct.

### ISSUE THREAD

**Issue by thisandthatXD** [shalzuth/RiskOfShame#6]
Sorry man not trying to keep you up late or bust balls lol. The loader seems to get stuck injecting it has the correct file path to my RiskofRain 2 in steam, but its placing the RiskofShame.zip and RiskofShame-master on my desktop. Keep in mind you don't have to do this now XD

i appreciate the abrupt reactions though keep up the good work it is an amazing mod while i was using it.

**Comment by shalzuth** [comment]
Can you try the latest version? https://github.com/shalzuth/RiskOfShame/releases/download/beta/RiskOfShame.Loader.exe

**Comment by thisandthatXD** [comment]
Working thanks.
